export const OPENCLAW_CRON_GATEWAY_TIMEOUT_MS = 20_000

export const OPENCLAW_CRON_DEFAULT_SESSION_MESSAGES_LIMIT = 1_000
export const OPENCLAW_CRON_OUTPUT_PROBE_MESSAGES_LIMIT = 30

export const OPENCLAW_CRON_REFRESH_INTERVAL_MS = 25_000
export const OPENCLAW_CRON_RUNNING_REFRESH_INTERVAL_MS = 2_000
export const OPENCLAW_CRON_RUN_SYNC_MAX_MS = 120_000
export const OPENCLAW_CRON_PENDING_OUTPUT_CHECK_ROUNDS = 3
export const OPENCLAW_CRON_INLINE_REFRESH_DELAY_MS = 300

export const OPENCLAW_CRON_RUN_HISTORY_PAGE_SIZE = 10
export const OPENCLAW_CRON_RUN_HISTORY_MESSAGES_LIMIT = 1_000

export const OPENCLAW_CRON_SIDEBAR_COUNTDOWN_REFRESH_INTERVAL_MS = 1_000

export const OPENCLAW_CRON_DEFAULT_AT_DELAY_MS = 5 * 60 * 1_000
export const OPENCLAW_CRON_DEFAULT_EVERY_INTERVAL = '1h'
export const OPENCLAW_CRON_DEFAULT_CRON_EXPRESSION = '0 9 * * 1'
export const OPENCLAW_CRON_DEFAULT_DELIVERY_CHANNEL = 'last'

export const OPENCLAW_CRON_SESSION_KEY_PREFIX = 'cron:'
